name: Deploy nnabla-rl

on:
  release:
    types: [published]

jobs:
  release-build:
    if: github.repository == 'sony/nnabla-rl'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy_requirements.txt
      - name: Build release distributions
        run: |
          python -m build --wheel
      - name: Temporarily upload release distribution
        uses: actions/upload-artifact@v3
        with:
          name: release-dists
          path: dist/
  deploy:
    if: github.repository == 'sony/nnabla-rl'
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    steps:
      - name: Retrieve temporarily uploaded release distributions
        uses: actions/download-artifact@v4.1.7
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
